name: Python Project CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.12']

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          # Кэшируем pip, чтобы не качать torch каждый раз
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m venv venv
          # Активация venv для Linux и Windows
          if [ "$RUNNER_OS" == "Windows" ]; then
            ./venv/Scripts/activate
            ./venv/Scripts/pip install -r requirements.txt
          else
            source venv/bin/activate
            pip install -r requirements.txt
          fi

      - name: Run code check
        run: |
          # Здесь вы можете добавить запуск тестов, например:
          # source venv/bin/activate && pytest
          echo "Зависимости установлены, проект готов к проверке!"