name: Python Project CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ['3.12']

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          # Кэшируем pip, чтобы не качать torch каждый раз
          cache: 'pip'
          
      - name: Install dependencies (Windows)
        if: runner.os == 'Windows'
        run: |
          python -m venv venv
          ./venv/Scripts/activate
          ./venv/Scripts/python -m pip install --upgrade pip
          ./venv/Scripts/pip install -r requirements.txt

      - name: Install dependencies (Linux/macOS)
        if: runner.os != 'Windows'
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run code check
        run: |
          echo "Зависимости установлены, проект готов к проверке!"